"""init

Revision ID: 71c31984e850
Revises: None
Create Date: 2025-11-04 16:03:10.736304

"""

import sqlalchemy as sa

from alembic import context
from alembic import op
from loguru import logger

# revision identifiers, used by Alembic.
revision = '71c31984e850'
down_revision = None


def upgrade():
    op.execute('CREATE SCHEMA IF NOT EXISTS __alembic_schema')
    op.execute('CREATE SCHEMA IF NOT EXISTS template_schema')

    schema_upgrades()

    # x-flag for data
    if context.get_x_argument(as_dictionary=True).get('data', None):
        data_upgrades()

    logger.opt(colors=True).info('Migration complete [ <green>OK</green> ]')


def downgrade():
    data_downgrades()
    schema_downgrades()


def schema_upgrades():
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'template_user_role',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('role_name', sa.String(), nullable=False, comment='Имя роли'),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('role_name'),
        schema='template_schema',
    )
    op.create_table(
        'template_user',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_name', sa.String(), nullable=False, comment='Имя юзера'),
        sa.Column(
            'role_id',
            sa.Integer(),
            server_default=sa.text('1'),
            nullable=True,
            comment='ФК на роль',
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ['role_id'], ['template_schema.template_user_role.id'], ondelete='SET NULL'
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_name'),
        schema='template_schema',
    )
    # ### end Alembic commands ###


def schema_downgrades():
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('template_user', schema='template_schema')
    op.drop_table('template_user_role', schema='template_schema')
    # ### end Alembic commands ###


def data_upgrades():
    """Add any optional data upgrade migrations here!"""
    pass


def data_downgrades():
    """Add any optional data downgrade migrations here!"""
    pass
